### 全局配置
mixed-port: 7897
allow-lan: true
mode: rule
log-level: warning
ipv6: false
find-process-mode: strict
### 如果使用的是裸核，需要将下面的注释去掉，方便ui界面的使用
# external-controller: 0.0.0.0:9988
# external-ui: ui
# external-ui-url: 'https://testingcf.jsdelivr.net/gh/Zephyruso/zashboard@releases/latest/download/dist.zip'
# secret: "114514yijiuyijiubayiling"
profile:
  store-selected: true
  store-fake-ip: true
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome

### DNS配置
dns:
  enable: true
  default-nameserver:      #基础DNS服务器，必须先有它才能使用域名类型的DNS配置，因此必须为IP，此处使用阿里云DNS
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver:         #在访问的国外网站没有匹配到任何域名规则，最终走了MATCH兜底规则时使用的DNS，为了确保不发生DNS泄漏和DNS污染，必须使用国外DNS
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  proxy-server-nameserver:         #解析代理节点时使用的DNS，为了使下面的respect-rules生效必须设置，最好设置为国内DNS，否则在代理的第一步就可能因为连接不上国外DNS而解析不出代理节点的IP，最终倒在起点
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:           #规则匹配到直连时使用的DNS，既然是可以直连的，当然要用国内DNS
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  respect-rules: true      #让连接DNS服务器时能够遵循规则，也就是通过代理节点连接到上面设置的国外DNS，因为直连可能连接不上
  always-real-ip:
    - "*.heiyu.space"
    - "*.lazycat.cloud"

# 嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+。v2ex。com"
  skip-domain:
    - "+.baidu。com"

# 入站  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  #使用nikki，混入全部不修改的情况，开启接口指定为nikki
  #使用仅内核自行修改下面三项为true
  #device: nikki
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  route-exclude-address:
    - 6.6.6.6/32
    - 2000::6666/128
  
  

# 节点筛选
# 按地区筛选
FilterHK: &FilterHK '^(?=.*(港|hk|hongkong|hong kong|🇭🇰))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点|落地|家宽|自建|×)).*$'
FilterJP: &FilterJP '^(?=.*(日|jp|japan|🇯🇵))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点|落地|家宽|自建|×)).*$'
FilterSG: &FilterSG '^(?=.*(新加坡|坡|狮城|SG|Singapore|🇸🇬))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点|落地|家宽|自建|×)).*$'
FilterUS: &FilterUS '^(?=.*(美|us|unitedstates|united states|🇺🇸))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点|落地|家宽|自建|×)).*$'
FilterSub: &FilterSub '^Sub.*'
FilterAll: &FilterAll '^(?=.*(.))(?!.*((?i)群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|(\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author)\b|(\d{4}-\d{2}-\d{2}|\d+G)))).*$'

Select: &Select {type: select, url: 'https://www.apple.com/library/test/success.html', disable-udp: false, hidden: false, include-all: true}
Auto: &Auto {type: url-test, url: 'https://www.apple.com/library/test/success.html', interval: 300, tolerance: 20, disable-udp: false, hidden: true, include-all: true}
Loadbalance: &Loadbalance {type: load-balance, url: 'https://www.apple.com/library/test/success.html', interval: 300, strategy: round-robin, disable-udp: false, hidden: true, include-all: true}

# 策略组
proxy-groups:
  # 主选择组
  - {name: 🚀 默认代理, type: select, proxies: [♻️ 香港自动, ♻️ 日本自动, ♻️ 狮城自动, ♻️ 美国自动, ♻️ 自动选择, ♻️ 手动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT], url: https://www.apple.com/library/test/success.html}

  # 应用分组
  - {name: 📹 YouTube, type: select, proxies: [♻️ 美国自动, ♻️ 香港自动, ♻️ 日本自动, ♻️ 狮城自动, ♻️ 自动选择, ♻️ 手动选择, 🚀 Sub优选节点-自动, 🚀 Sub优选节点-手动, 🌐 全部节点, DIRECT], icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Streaming.png}
  - {name: 🍀 Google, type: select, proxies: [♻️ 香港自动, ♻️ 日本自动, ♻️ 狮城自动, ♻️ 美国自动, ♻️ 自动选择, ♻️ 手动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT], icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Google.png}
  - {name: 🤖 AI, type: select, proxies: [♻️ 日本自动, ♻️ 狮城自动, ♻️ 美国自动, ♻️ 自动选择, ♻️ 手动选择, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT], icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/OpenAI.png}
  - {name: 👨🏿‍💻 GitHub, type: select, proxies: [♻️ 香港自动, ♻️ 日本自动, ♻️ 狮城自动, ♻️ 美国自动, ♻️ 自动选择, ♻️ 手动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT], icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Github.png}
  - {name: 🪟 Microsoft, type: select, proxies: [♻️ 香港自动, ♻️ 日本自动, ♻️ 狮城自动, ♻️ 美国自动, ♻️ 自动选择, ♻️ 手动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT], icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Microsoft.png}
  - {name: 🐬 OneDrive, type: select, proxies: [♻️ 香港自动, ♻️ 日本自动, ♻️ 狮城自动, ♻️ 美国自动, ♻️ 自动选择, ♻️ 手动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT], icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Onedrive.png}
  - {name: 📲 Telegram, type: select, proxies: [♻️ 香港自动, ♻️ 日本自动, ♻️ 狮城自动, ♻️ 美国自动, ♻️ 自动选择, ♻️ 手动选择, 🚀 Sub优选节点-自动, 🚀 Sub优选节点-手动, 🌐 全部节点, DIRECT], icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Telegram.png}
  - {name: 💢 广告拦截, type: select, proxies: [DIRECT, REJECT]}
  - {name: 🐟 漏网之鱼, type: select, proxies: [🚀 默认代理, ♻️ 香港自动, ♻️ 日本自动, ♻️ 狮城自动, ♻️ 美国自动, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT]}

  # Sub分组
  - {name: 🚀 Sub优选节点-自动, <<: *Auto, filter: *FilterSub}
  - {name: 🚀 Sub优选节点-手动, <<: *Select, filter: *FilterSub}

  # 自动选择 - 按地区
  - {name: ♻️ 香港自动, <<: *Auto, filter: *FilterHK, icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/HK.png}
  - {name: ♻️ 日本自动, <<: *Auto, filter: *FilterJP, icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/JP.png}
  - {name: ♻️ 狮城自动, <<: *Auto, filter: *FilterSG, icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/SG.png}
  - {name: ♻️ 美国自动, <<: *Auto, filter: *FilterUS, icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/US.png}

  # 手动选择节点
  - {name: ♻️ 自动选择, <<: *Auto, filter: *FilterAll}
  - {name: ♻️ 手动选择, <<: *Select, filter: *FilterAll}
  - {name: 🌐 全部节点, <<: *Select}

  # 手动选择地区节点
  - {name: 🇭🇰 香港节点, <<: *Select, filter: *FilterHK}
  - {name: 🇯🇵 日本节点, <<: *Select, filter: *FilterJP}
  - {name: 🇸🇬 狮城节点, <<: *Select, filter: *FilterSG}
  - {name: 🇺🇲 美国节点, <<: *Select, filter: *FilterUS}

### 规则配置
RuleSet_classical: &RuleSet_classical {type: http, behavior: classical, interval: 43200, format: text, proxy: 🚀 默认代理}
RuleSet_domain: &RuleSet_domain {type: http, behavior: domain, interval: 43200, format: text, proxy: 🚀 默认代理}
RuleSet_ipcidr: &RuleSet_ipcidr {type: http, behavior: ipcidr, interval: 43200, format: text, proxy: 🚀 默认代理}
RuleSet_filter: &RuleSet_filter {type: http, behavior: domain, interval: 43200, format: mrs, proxy: 🚀 默认代理}

# 订阅规则
rule-providers:
  fakeip-filter:
    <<: *RuleSet_filter
    url: https://testingcf.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/fakeip-filter.mrs
    path: ./rule_set/other_ruleset/fakeip-filter.mrs

  cn:
    <<: *RuleSet_filter
    url: https://testingcf.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/cn.mrs
    path: ./rule_set/other_ruleset/cn.mrs

  private:
    <<: *RuleSet_filter
    url: https://testingcf.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/private.mrs
    path: ./rule_set/other_ruleset/private.mrs

  trackerslist:
    <<: *RuleSet_filter
    url: https://testingcf.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/trackerslist.mrs
    path: ./rule_set/other_ruleset/trackerslist.mrs

  private_ip:
    <<: *RuleSet_classical
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
    path: ./rule_set/sukkaw_ruleset/private_ip.txt

  private_domain:
    <<: *RuleSet_domain
    url: https://ruleset.skk.moe/Clash/domainset/direct.txt
    path: ./rule_set/sukkaw_ruleset/private_domain.txt

  proxylite:
    <<: *RuleSet_domain
    url: https://ruleset.skk.moe/Clash/domainset/global.txt
    path: ./rule_set/sukkaw_ruleset/proxylite.txt

  ai:
    <<: *RuleSet_classical
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./rule_set/sukkaw_ruleset/ai.txt

  github_domain:
    <<: *RuleSet_domain
    url: https://ruleset.skk.moe/Clash/domainset/github.txt
    path: ./rule_set/sukkaw_ruleset/github_domain.txt

  youtube_domain:
    <<: *RuleSet_classical
    url: https://ruleset.skk.moe/Clash/non_ip/stream.txt
    path: ./rule_set/sukkaw_ruleset/youtube_domain.txt

  google_domain:
    <<: *RuleSet_domain
    url: https://ruleset.skk.moe/Clash/domainset/google.txt
    path: ./rule_set/sukkaw_ruleset/google_domain.txt

  onedrive_domain:
    <<: *RuleSet_domain
    url: https://ruleset.skk.moe/Clash/domainset/microsoft.txt
    path: ./rule_set/sukkaw_ruleset/onedrive_domain.txt

  microsoft_domain:
    <<: *RuleSet_classical
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft.txt
    path: ./rule_set/sukkaw_ruleset/microsoft_domain.txt

  apple_domain:
    <<: *RuleSet_classical
    url: https://ruleset.skk.moe/Clash/non_ip/apple_services.txt
    path: ./rule_set/sukkaw_ruleset/apple_domain.txt

  telegram_domain:
    <<: *RuleSet_classical
    url: https://ruleset.skk.moe/Clash/non_ip/telegram.txt
    path: ./rule_set/sukkaw_ruleset/telegram_domain.txt

  geolocation-!cn:
    <<: *RuleSet_classical
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
    path: ./rule_set/sukkaw_ruleset/geolocation-!cn.txt

  cn_domain:
    <<: *RuleSet_domain
    url: https://ruleset.skk.moe/Clash/domainset/cn.txt
    path: ./rule_set/sukkaw_ruleset/cn_domain.txt

  cn_ip:
    <<: *RuleSet_classical
    url: https://ruleset.skk.moe/Clash/ip/domestic.txt
    path: ./rule_set/sukkaw_ruleset/cn_ip.txt

  ad:
    <<: *RuleSet_domain
    url: https://ruleset.skk.moe/Clash/domainset/reject.txt
    path: ./rule_set/sukkaw_ruleset/ad.txt

# 分流规则
rules:
  # 自定义规则
  - DOMAIN-SUFFIX,heiyu.space,DIRECT
  - DOMAIN-SUFFIX,lazycat.cloud,DIRECT
  - DOMAIN-SUFFIX,qichiyu.com,🚀 默认代理

  # 规则集
  - RULE-SET，private_ip，DIRECT,no-resolve
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,proxylite,🚀 默认代理
  - RULE-SET，ai，🤖 AI
  - RULE-SET,github_domain,👨🏿‍💻 GitHub
  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET，google_domain,🍀 Google
  - RULE-SET,onedrive_domain,🐬 OneDrive
  - RULE-SET,microsoft_domain,🪟 Microsoft
  - RULE-SET,apple_domain,DIRECT
  - RULE-SET,telegram_domain,📲 Telegram
  - RULE-SET，geolocation-!cn,🚀 默认代理
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,cn_ip,DIRECT
  - RULE-SET,ad,💢 广告拦截
  - MATCH,🐟 漏网之鱼
